### ISSUE TITLE
FIDDLE output format

### ISSUE THREAD

**Issue by MattHodgman** [MLD3/FIDDLE-experiments#4]
I tried to reproduce the FIDDLE experiments, however, the output X.npz is not a sparse matrix (and thus won't load using spicy.sparse.load_npz(), so I used lumpy.load()). X.npz contains:

X['data']: a long vector of only 1's
X['shape']: a vector describing the correct dimensions of the expected output tensor
X['fill_value']: a vector with just a single zero in it
X['coords']: a vector with 3 rows and the same number of columns as the length of X['data']

Is this an error or do I need to process this output first in order to get the sparse N x L x D tensor? I did not see anything in the documentation or paper regarding this. Cheers.

**Comment by shengpu-tang** [comment]
Hello, please use the `sparse` package instead of `scipy.sparse`. scipy sparse only supports two dimensional sparse matrices, but here X is a three dimensional sparse tensor (recall the dimensions are (N, L, D) ). 

https://sparse.pydata.org/en/stable/

**Comment by MattHodgman** [comment]
Thank you!
