### ISSUE TITLE
IHM Benchmark: Location of "train_listfile.csv", etc not clear. 

### ISSUE THREAD

**Issue by josephcscarpa** [MLD3/FIDDLE-experiments#6]
I am trying to reproduce your results using these instructions: https://github.com/MLD3/FIDDLE-experiments/tree/master/mimic3_experiments. 

However, when running the IHM_Benchmark notebook, I get an error [Errno 2] No such file or directory 'train_listfile.csv'

I am not sure at which step the csv was supposed to be created since the other steps do not appear to generate it anywhere. Any help would be greatly appreciated.

**Comment by shengpu-tang** [comment]
Hello, the train_listfile.csv is located at mimic3_experiments/1_data_extraction/resources/train_listfile.csv

It should be at the same place of the IHM_benchmark notebook you are trying to run.

**Comment by josephcscarpa** [comment]
I didn't see it at first, and when I triple-checked, I saw it. Sorry to bother you with this issue and thank you for your fast response!
